# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import echo_agent_pb2 as echo__agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in echo_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoAgentServiceStub:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/echo_agent.v1.EchoAgentService/CreateAgent',
                request_serializer=echo__agent__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.AgentHandle.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/echo_agent.v1.EchoAgentService/DeleteAgent',
                request_serializer=echo__agent__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.DeleteAgentResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/echo_agent.v1.EchoAgentService/Invoke',
                request_serializer=echo__agent__pb2.InvokeRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/echo_agent.v1.EchoAgentService/Stream',
                request_serializer=echo__agent__pb2.InvokeRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/echo_agent.v1.EchoAgentService/Resume',
                request_serializer=echo__agent__pb2.ResumeRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.StreamResume = channel.unary_stream(
                '/echo_agent.v1.EchoAgentService/StreamResume',
                request_serializer=echo__agent__pb2.ResumeRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.AgentEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/echo_agent.v1.EchoAgentService/Cancel',
                request_serializer=echo__agent__pb2.CancelRequest.SerializeToString,
                response_deserializer=echo__agent__pb2.CancelResponse.FromString,
                _registered_method=True)


class EchoAgentServiceServicer:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def CreateAgent(self, request, context):
        """按 AgentConfig（+ 可选 RuntimeOptions）调用注入的 factory 创建 Agent，返回 agent_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """销毁进程内 Agent 实例（宿主业务结束时调用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """同步执行一轮（需 session_id）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """流式执行；事件由 Adapter 从 AgentResult 流映射
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """HITL 恢复（对齐 Agent.resume）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamResume(self, request, context):
        """HITL 流式恢复（对齐 Agent.stream_resume）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """中止指定 session 上正在进行的当轮执行（非 HITL resume 取消）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=echo__agent__pb2.CreateAgentRequest.FromString,
                    response_serializer=echo__agent__pb2.AgentHandle.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=echo__agent__pb2.DeleteAgentRequest.FromString,
                    response_serializer=echo__agent__pb2.DeleteAgentResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=echo__agent__pb2.InvokeRequest.FromString,
                    response_serializer=echo__agent__pb2.AgentResponse.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=echo__agent__pb2.InvokeRequest.FromString,
                    response_serializer=echo__agent__pb2.AgentEvent.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=echo__agent__pb2.ResumeRequest.FromString,
                    response_serializer=echo__agent__pb2.AgentResponse.SerializeToString,
            ),
            'StreamResume': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamResume,
                    request_deserializer=echo__agent__pb2.ResumeRequest.FromString,
                    response_serializer=echo__agent__pb2.AgentEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=echo__agent__pb2.CancelRequest.FromString,
                    response_serializer=echo__agent__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo_agent.v1.EchoAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('echo_agent.v1.EchoAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EchoAgentService:
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/CreateAgent',
            echo__agent__pb2.CreateAgentRequest.SerializeToString,
            echo__agent__pb2.AgentHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/DeleteAgent',
            echo__agent__pb2.DeleteAgentRequest.SerializeToString,
            echo__agent__pb2.DeleteAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/Invoke',
            echo__agent__pb2.InvokeRequest.SerializeToString,
            echo__agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/Stream',
            echo__agent__pb2.InvokeRequest.SerializeToString,
            echo__agent__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/Resume',
            echo__agent__pb2.ResumeRequest.SerializeToString,
            echo__agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/StreamResume',
            echo__agent__pb2.ResumeRequest.SerializeToString,
            echo__agent__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/echo_agent.v1.EchoAgentService/Cancel',
            echo__agent__pb2.CancelRequest.SerializeToString,
            echo__agent__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
